2020-05-14 03:33:11,582 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:33:26,075 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:34:15,367 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:35:49,733 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:36:19,846 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:41:13,556 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:52:13,994 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:52:50,409 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:53:54,420 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 03:55:49,959 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:01:40,821 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:01:43,094 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 24, in ez
    tech = Tech.check(st_row=Tech.query.order_by(func.random()).limit(2))
TypeError: check() missing 1 required positional argument: 'self'
2020-05-14 04:02:47,366 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:02:48,422 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 24, in ez
    tech = Tech.check(st_row=Tech.query.order_by(func.random()).limit(2))
TypeError: check() missing 1 required positional argument: 'self'
2020-05-14 04:05:05,645 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:05:06,730 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 24, in ez
    tech = Tech.check("Tech", st_row=Tech.query.order_by(func.random()).limit(2))
  File "C:\Users\s2905\Desktop\EA Project\abc\app\models.py", line 126, in check
    nd_row = self.query.filter(~Tech.picture_name.in_([str(tech_data[0]), str(tech_data[1])])) \
AttributeError: 'str' object has no attribute 'query'
2020-05-14 04:05:20,388 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:10:01,639 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:10:02,700 ERROR: Exception on / [GET] [in C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\s2905\Desktop\EA Project\abc\app\main\routes.py", line 25, in ez
    techv2 = Tech.query.filter(~Tech.picture_name.in_([tech])).order_by(func.random()).limit(2)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 604, in in_
    return self.operate(in_op, other)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 218, in operate
    return op(self.comparator, *other, **kwargs)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 1260, in in_op
    return a.in_(b)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 604, in in_
    return self.operate(in_op, other)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\orm\properties.py", line 341, in operate
    return op(self.__clause_element__(), *other, **kwargs)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 1260, in in_op
    return a.in_(b)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 604, in in_
    return self.operate(in_op, other)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 741, in operate
    return op(self.comparator, *other, **kwargs)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 1260, in in_op
    return a.in_(b)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 604, in in_
    return self.operate(in_op, other)
  File "<string>", line 1, in <lambda>
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\type_api.py", line 67, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "C:\Users\s2905\Desktop\EA Project\abc\venv\lib\site-packages\sqlalchemy\sql\default_comparator.py", line 204, in _in_impl
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: in_() accepts either a list of expressions, a selectable, or an "expanding" bound parameter: <flask_sqlalchemy.BaseQuery object at 0x0000023747C2AB50>
2020-05-14 04:13:28,861 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:16:57,896 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
2020-05-14 04:18:47,977 INFO: Microblog startup [in C:\Users\s2905\Desktop\EA Project\abc\app\__init__.py:74]
