2020-05-02 15:00:02,278 ERROR: Exception on /phone [GET] [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\app\main\routes.py", line 51, in phone
    return render_template('TFocus/phone.html', title=_('Phone'))
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\app\templates\TFocus\phone.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\app\templates\base.html", line 73, in block "content"
    {% block current_app_content %}{% endblock %}
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\app\templates\TFocus\phone.html", line 5, in block "current_app_content"
    <li><a href="{{ url_for('#') }}"><font color="#000000">{{ _('Apple iPhone XS ô§ôúéä HKÅê3899ÅIíÔäﬂâﬂ iPhone SEÅH') }}</font></a></li>
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '#'. Did you mean 'auth.reset_password_request' instead?
2020-05-02 15:00:29,892 INFO: Microblog startup [in E:\ive\s2\ITP4924_IT_ICT_1( Web Application Development )\abc\app\__init__.py:74]
